CREATE TABLE stg.FactActuals(
	[factactuals_ID] [int] IDENTITY(1,1) NOT NULL,
	[claim_Exposure_No] [varchar](64) NOT NULL,
	[claimNumber] [varchar](64) NOT NULL,
	[exposure_No] [varchar](64) NOT NULL,
	[workmatternumber] [varchar](64) NOT NULL,
	[portfolio_Cd] [varchar](64) NULL,
	[policy_No] [varchar](64) NULL,
	[policyEffectiveDate] [date] NULL,
	[Policy_Expiration_Dt] [date] NULL,
	[NAIC_Cd] [varchar](64) NULL,
	[Business_Type_Cd] [varchar](64) NULL,
	[valuationdate] [date] NULL,
	[paidLoss] [decimal](14, 2) NULL,
	[paidexpenseinlimits] [decimal](14, 2) NULL,
	[paidCoverageDJExpense] [decimal](14, 2) NULL,
	[paidAdjustingExpense] [decimal](14, 2) NULL,
	[recoverySalvage] [decimal](14, 2) NULL,
	[recoverySubrogationLoss] [decimal](14, 2) NULL,
	[recoveryDeductibleLoss] [decimal](14, 2) NULL,
	[recoverySubrogationExpense] [decimal](14, 2) NULL,
	[caseLoss] [decimal](14, 2) NULL,
	[caseAdjustingExpense] [decimal](14, 2) NULL,
	[caseCoverageDJExpense] [decimal](14, 2) NULL,
    Insert_Date                   datetime          DEFAULT (getdate()) NOT NULL,
    CONSTRAINT PK_stg_factactuals PRIMARY KEY CLUSTERED (factactuals_ID)
)
