CREATE TABLE stg.Reinsurance(
	[reinsurance_ID] [int] IDENTITY(1,1) NOT NULL,
	[claimNumber] [varchar](64) NOT NULL,
	[exposure_No] [varchar](64) NOT NULL,
	[sapiensReinsurerID] [int] NULL,
	[sapiensBrokerID] [int] NULL,
	[sapiensPoolID] [int] NULL,
	[sectionReferenceNumber] [varchar](64) NULL,
	[retentionInd] [varchar](64) NULL,
	[entrydate] [date] NULL,
	[CashFlowBatchID] [int] NULL,
	[creditProvisionPercent] [decimal](14, 2) NULL,
	[reinsurerName] [varchar](64) NULL,
	[pool_Name] [varchar](64) NULL,
	[brokerName] [varchar](64) NULL,
	[relatedClaimNumber] [varchar](64) NULL,
	[projectedCededTotalPaidLossExInLimits] [decimal](14, 2) NULL,
	[projectedCededTotalPaidDefExpense] [decimal](14, 2) NULL,
	[projectedCededPaidCoverageDJExpense] [decimal](14, 2) NULL,
	CededFactsHashKey                        AS                CONVERT(VARCHAR(32), HashBytes('MD5', CONCAT(claimNumber, ' ', exposure_No, ' ', CAST(sapiensReinsurerID AS VARCHAR), ' ', CAST(sapiensBrokerID AS VARCHAR), ' ', CAST(sapiensPoolID AS VARCHAR), ' ', sectionReferenceNumber, ' ', retentionInd, ' ', CAST(entryDate AS VARCHAR), ' ', creditProvisionPercent, ' ', reinsurerName, ' ', pool_Name, ' ', brokerName, ' ', relatedClaimNumber, ' ', CAST(projectedCededTotalPaidLossExInLimits AS VARCHAR), ' ', CAST(projectedCededTotalPaidDefExpense AS VARCHAR), ' ', CAST(projectedCededPaidCoverageDJExpense AS VARCHAR))),2) PERSISTED,
    Insert_Date                              datetime          DEFAULT (getdate()) NOT NULL,
    CONSTRAINT PK_stg_reinsurance PRIMARY KEY CLUSTERED (reinsurance_ID)
)